CREATE TABLE "user" (
  id BIGSERIAL NOT NULL,
  username VARCHAR(45) NOT NULL,
  password VARCHAR(255) NOT NULL,
  enabled BOOLEAN NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE user_role (
  id BIGSERIAL NOT NULL,
  user_id BIGINT NOT NULL REFERENCES "user" (id),
  role VARCHAR(45) NOT NULL,
  PRIMARY KEY (id)
);